% PARAMETERS for PLASTIC: This file contains
% major simulation parameters that make more
% specific modifications to the model.
% Guy Billings 17/02/2007

% Master timestep: This should not be changed, although in general smaller timesteps
% will give more accuracy (but will take much longer). This value represents a good
% tradeoff. The intergration method is forward Euler. 

const_master=0.0001; 

% Setup the random number generator:

%r_seed=0; 				      % Random numbers generated by PLASTIC are always initialised at the same point
r_seed=sum(100*clock); 		  % Change PLASTIC random number generator initialisation for each run
%rand('state',0); 			  % Initialise the MATLAB random number generator in the same place for each run
rand('state',sum(100*clock)); % Change the initialisation of the MATLAB random number generator for each run

% Synaptic conductance and input resistance for the cells

synaptic_cond=200e-12; %(S)		
input_resistance=100e6; %(Ohm)

% This is the main simulation parameter array: Some of these are specified in setup.m

params(1)=mean_int;							% Mean interval (s)
params(2)=const_master;	 					% Simulation timestep (s)
params(3)=input_resistance*synaptic_cond; 	% Gmax - dimnesionless;
params(4)=0.005; 							% Tex (s) 
params(5)=-0.074; 							% Vrest (V)
params(6)=params(5); 		 				% Vinit (V)
params(7)=0.0; 								% excitatory Reversal potential (Eex) (V)
params(8)=params(5);						% inhibitory reversal potential (Ein) (V)
params(9)=-0.054; 							% spike_thresh (V)
params(10)=0.02; 							% membrane time const (s)
params(11)=params(10); 						% depression time const (s)
params(12)=params(10); 						% potentiation time const (s)
params(13)=0.003; 							% Potentiation rate l_rate_pot (dimensionless)
params(14)=1.05*params(13);					% depotentiation rate  (dimensionless)
params(15)=sim_steps;						% Simulation timesteps (outer loop)
params(17)=input_base; 						% r0 (Hz)
params(18)=input_peak; 						% r1 (Hz)
params(19)=inputs/10; 						% sigma (Dimensionless; width of stimulus - protocol 1)
params(20)=stim_loc;						% Stimulus location for protocol 4
params(21)=0;	 							% noise freqency (Hz)
params(22)=0;	 							% Noise input conductance (Dimnesionless; as fraction of input resistance)
params(24)=stim_dur;	 					% stimulus cycle time (protocol 2)
params(28)=0.015; 							% Standard deviation of update in weight dependent case
params(29)=0.2e-12*input_resistance; 		% weight dependent potentiation conductance increment (Dimensionless) 
params(30)=0.002;							% weight dependent depression factor (Dimensionless)
params(33)=input_resistance*10e-12; 		% single unit conductance * input resistance (dimensionless)
params(34)=1;	     	 		 			% Gaussian noise correlation  time(s)
params(35)=1e-4;	 	 					% Gaussian noise standard deviation 

params(16)=corr_com; 						% correlated frequency component (Hz) - protocol 0
params(38)=zero_base;						% Protocol 0, base rate
params(39)=zero_var;						% Variance in the base rate
 
params(23)=protocol;  	% Stimulus protocol

% We can disable plasticity here

params(25)=1;  	% feedforward plasticity flag '0' to disable
params(26)=0;  	% recurrent connection plasticity flag (inhibitory)
params(36)=0;	% antagonist connection plasticity flag (excitatory)
params(37)=mult;% Excitatory recurrent weight multiplication factor

params(27)=wdep;	% weight dependence of learning rule

% Perturbs feedforward weights with Gaussian noise (OU process) with correlation time
% and standard deviation set by params(34) and params(35)

params(31)=-1;  	% feedforward perturbation flag delay (dt) '-1' turns noise off
params(32)=-1;		% recurrent connections perturbation flag delay (dt)
